name: Minimal usage
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: eessi/github-action-eessi@v3
      with:
        eessi_stack_version: '2025.06'
    - name: Build and test our code
      run: |
        module load HDF5 CMake buildenv
        mkdir build
        cd build/
        cmake ..
        make -j
        ctest --output-on-failure --verbose
      shell: bash
